<?php
// $Id$

/**
 * @file
 * Enables Alfresco and Drupal integration.
 *
 * Contents of this file
 * =====================
 * 0. Constants, includes and views support
 * 1. Help hooks
 * 2. Node info and permissions
 * 3. Menu hooks
 * 4. Cron hooks
 * 5. Theme hooks
 * 6. Files helper functions
 * 7. Utils helper functions
 * 8. Debug helper functions
 */

// ------------------------------------------------------------------
// =0 Constants, includes and views support
// ------------------------------------------------------------------

// Relative path to Alfresco PHP Library
if (!defined('ALFRESCO_PHP_LIBRARY_PATH')) {
  define('ALFRESCO_PHP_LIBRARY_PATH', 'alfresco-php-sdk');
}

// Default value for alfresco_debug_output variable.
define('ALFRESCO_DEBUG_OUTPUT', TRUE);

// Alfresco file downloads methods.
// @see http://wiki.alfresco.com/wiki/URL_Addressability
define('ALFRESCO_FILE_DOWNLOADS_MODULE', 1);  // Private transfer
define('ALFRESCO_FILE_DOWNLOADS_GUEST',  2);  // Direct Guest URL
define('ALFRESCO_FILE_DOWNLOADS_TICKET', 3);  // Direct Ticket URL

// Alfresco types
define('ALFRESCO_TYPE_CONTENT', '{http://www.alfresco.org/model/content/1.0}content');
define('ALFRESCO_TYPE_FOLDER',  '{http://www.alfresco.org/model/content/1.0}folder');

// Regex string for any variety of ISO and DATETIME formats
// (from date_api.module)
define('ALFRESCO_REGEX_DATE_LOOSE', '/(\d{4})-?(\d{2})-?(\d{2})([T\s]?(\d{2}):?(\d{2}):?(\d{2})?(\.\d+)?(Z|[\+\-]\d{2}:?\d{2})?)?/');

// Alfresco Node UUID regex
define('ALFRESCO_REGEX_NODE_UUID', '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}');


// Include required files
if (function_exists('drupal_get_path')) {
  $path = drupal_get_path('module', 'alfresco');
  require_once $path .'/alfresco.content.inc';
  require_once $path .'/alfresco.ws.inc';
}

/**
 * Implementation of hook_views_api().
 */
function alfresco_views_api() {
  return array(
    'api' => 2,
  );
}

// ------------------------------------------------------------------
// =1 Help hooks
// ------------------------------------------------------------------

/**
 * Implementation of hook_help().
 */
function alfresco_help($path, $arg) {

  switch ($path) {
    case 'admin/help#alfresco':
      return '<p>'. t('Alfresco and Drupal integration.') .'</p>';
  }
}

// ------------------------------------------------------------------
// =2 Node info and permissions hooks
// ------------------------------------------------------------------

/**
 * Implementation of hook_node_info().
 *
 * Provides a new 'alfresco_item' node content type.
 */
function alfresco_node_info() {

  return array(
    'alfresco_item' => array(
      'name'        => t('Alfresco item'),
      'module'      => 'alfresco',
      'description' => t('An <em>alfresco item</em> is a reference to node stored in Alfresco repository. Alfresco node can be content items o spaces.'),
      'has_title'   => TRUE,
      'title_label' => t('Title'),
      'has_body'    => TRUE,
      'body_label'  => t('Body'),
    )
  );
}

/**
 * Implementation of hook_perm().
 *
 * Since we are limiting the ability to create new nodes to certain users,
 * we need to define what those permissions are here. We also define a permission
 * to allow users to edit the nodes they created.
 */
function alfresco_perm() {

  return array(
    'administer alfresco',
    'create alfresco content',
    'delete own alfresco content',
    'delete any alfresco content',
    'download alfresco content',
    'edit own alfresco content',
    'edit any alfresco content',
  );
}

/**
 * Implementation of hook_access().
 *
 * Node modules may implement node_access() to determine the operations
 * users may perform on nodes. This example uses a very common access pattern.
 */
function alfresco_access($op, $node, $account) {

  if ($op == 'create') {
    return user_access('create alfresco content', $account);
  }

  if ($op == 'update') {
    if (user_access('edit any alfresco content', $account) || (user_access('edit own alfresco content', $account) && ($account->uid == $node->uid))) {
      return TRUE;
    }
  }

  if ($op == 'delete') {
    if (user_access('delete any alfresco content', $account) || (user_access('delete own alfresco content', $account) && ($account->uid == $node->uid))) {
      return TRUE;
    }
  }
}

// ------------------------------------------------------------------
// =3 Menu hooks
// ------------------------------------------------------------------

/**
 * Implementation of hook_menu().
 */
function alfresco_menu() {
  $items['admin/settings/alfresco'] = array(
    'title' => 'Alfresco',
    'description' => 'Configure Alfresco.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alfresco_admin_overview'),
    'access arguments' => array('administer alfresco'),
    'file' => 'alfresco.admin.inc',
  );

  $items['admin/settings/alfresco/repository'] = array(
    'title' => 'Repository',
    'weight' => 1,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/settings/alfresco/display'] = array(
    'title' => 'Display',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alfresco_admin_display'),
    'access arguments' => array('administer alfresco'),
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
    'parent' => 'admin/settings/alfresco',
    'file' => 'alfresco.admin.inc',
  );

  $items['admin/settings/alfresco/advanced'] = array(
    'title' => 'Advanced',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alfresco_admin_advanced'),
    'access arguments' => array('administer alfresco'),
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
    'parent' => 'admin/settings/alfresco',
    'file' => 'alfresco.admin.inc',
  );

  $items['node/%alfresco_node/download/%alfresco_name'] = array(
    'title' => 'Download',
    'page callback' => 'alfresco_page_download',
    'page arguments' => array(1),
    'access callback' => '_alfresco_download_access',
    'access arguments' => array(1),
    'weight' => 5,
    'type' => MENU_LOCAL_TASK,
    'file' => 'alfresco.pages.inc',
  );

  $items['node/%alfresco_node/sync'] = array(
    'title' => 'Synchronize',
    'page callback' => 'alfresco_page_sync',
    'page arguments' => array(1),
    'access callback' => '_alfresco_administer_access',
    'access arguments' => array(1),
    'weight' => 6,
    'type' => MENU_LOCAL_TASK,
    'file' => 'alfresco.pages.inc',
  );

  $items['node/%alfresco_node/details'] = array(
    'title' => 'Details',
    'page callback' => 'alfresco_page_details',
    'page arguments' => array(1),
    'access callback' => '_alfresco_administer_access',
    'access arguments' => array(1),
    'weight' => 7,
    'type' => MENU_LOCAL_TASK,
    'file' => 'alfresco.pages.inc',
  );

  return $items;
}

function _alfresco_download_access($node) {
  return user_access('download alfresco content') && ($node->type == 'alfresco_item' && !empty($node->cm_content));
}

function _alfresco_administer_access($node) {
  return user_access('administer alfresco') && ($node->type == 'alfresco_item');
}

/**
 * Menu callback; loads an alfresco node object.
 *
 * @see http://drupal.org/node/209056
 */
function alfresco_node_load($arg) {

  if (!is_numeric($arg)) {
    return FALSE;
  }
  $node = node_load($arg);

  if (!$node || $node->type != 'alfresco_item') {
    return FALSE;
  }
  return $node;
}

/**
 * Menu callback; loads the name of alfresco node object.
 */
function alfresco_name_load($arg) {
  return $arg;
}

/**
 * Returns the name (filename) of the currently alfresco node.
 *
 * @see http://drupal.org/node/109153#to_arg
 */
function alfresco_name_to_arg($arg) {

  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $node = node_load(arg(1));
    if ($node && $node->type == 'alfresco_item') {
      return $node->cm_name;
    }
  }
  return $arg;
}

// ------------------------------------------------------------------
// =4 Cron hooks
// ------------------------------------------------------------------

/**
 * Implementation of hook_cron().
 *
 * @see ALFRESCO_SYNC_TIME
 * @see ALFRESCO_SYNC_LIMIT
 */
function alfresco_cron() {

  if (variable_get('alfresco_sync_enabled', FALSE)) {
    $limit = (int)variable_get('alfresco_sync_cron_limit', 100);
    $refresh = (int)variable_get('alfresco_sync_cron_refresh', 21600);

    $result = db_query_range('SELECT nid FROM {alfresco_node} WHERE timestamp < %d ORDER BY timestamp DESC', time() - $refresh, 0, $limit);
    while ($node = db_fetch_object($result)) {
      alfresco_sync_node($node);
    }
  }
}

// ------------------------------------------------------------------
// =5 Theme hooks
// ------------------------------------------------------------------

/**
 * Implementation of hook_theme()
 */
function alfresco_theme() {
  return array(
    'alfresco_properties_table' => array(
      'arguments' => array('form' => NULL),
      'file' => 'alfresco.admin.inc',
    ),
    'alfresco_teaser' => array(
      'arguments' => array('node'),
      'file' => 'alfresco.theme.inc',
    ),
    'alfresco_display' => array(
      'arguments' => array('node'),
      'file' => 'alfresco.theme.inc',
    ),
  );
}

// ------------------------------------------------------------------
// =6 Files helper functions
// ------------------------------------------------------------------

/**
 * Return The URL for download the alfresco file.
 */
function alfresco_url_download($node) {

  if ($node->type == 'alfresco_item' && !empty($node->cm_content)) {
    return 'node/'. $node->nid .'/download/'. $node->cm_name;
  }
}

/**
 * Transfer file using http to client. Pipes a file through Drupal to the client.
 *
 * @see file_transfer()
 * @see http://w-shadow.com/blog/2007/08/12/how-to-force-file-download-with-php/
 * @see http://www.phpclasses.org/browse/file/9051.html
 * @see http://www.php-mysql-tutorial.com/php-tutorial/php-read-remote-file.php
 * @see http://htmlblog.net/10-code-snippets-for-php-developers/
 */
function alfresco_file_transfer($node) {
  if (ob_get_level()) {
    ob_end_clean();
  }

  $alf_node = alfresco_service_load_node($node->reference);
  if (!$alf_node) {
    drupal_not_found();
    exit();
  }

  $alf_data = $alf_node->cm_content;
  if (!$alf_data) {
    drupal_not_found();
    exit();
  }

  $name = $alf_node->cm_name;
  $url  = $alf_data->url;
  $size = $alf_data->size;
  $mime = $alf_data->mimetype;

  drupal_set_header('Content-Type: '. $mime);
  drupal_set_header('Content-Length: '. $size);
  //drupal_set_header('Content-Disposition: attachment; filename="' . $name . '"');

  // Transfer file in 1024 byte chunks to save memory usage.
  if ($fd = fopen($url, 'rb')) {
    while (!feof($fd)) {
      print fread($fd, 1024);
    }
    fclose($fd);
  }
  else {
    drupal_not_found();
  }
  exit();
}

// ------------------------------------------------------------------
// =7 Utils helper functions
// ------------------------------------------------------------------

/**
 * Verify the syntax of the given Alfresco Node Reference.
 *
 * @param $reference
 *   A string containing an Alfresco Node Reference.
 * @return
 *   TRUE if the reference is in a valid format.
 *
 * @see http://wiki.alfresco.com/wiki/Web_Service_Data_Types
 */
function alfresco_valid_reference($reference) {

  $pattern = "/^\w+:\/\/\w+\/". ALFRESCO_REGEX_NODE_UUID ."$/";
  return preg_match($pattern, $reference);
}

/**
 * Parse a given Alfresco Node Reference.
 *
 * @param $reference
 *   A string containing an Alfresco Node Reference.
 * @return
 *   FALSE, if the reference is in an invalid format. Otherwise, a
 *   keyed array containing the components:
 *    'reference' - Reference (same)
 *    'scheme'    - Scheme.
 *    'address'   - Address.
 *    'uuid'      - UUID.
 *   If the component parameter is specified a string is returned
 *   instead of an array.
 */
function alfresco_parse_reference($reference, $component = '') {

  $pattern = "/^(\w+):\/\/(\w+)\/(". ALFRESCO_REGEX_NODE_UUID .")$/";
  if (preg_match($pattern, $reference, $matches)) {
    $info = array();
    $info['reference'] = $matches[0];
    $info['scheme']    = $matches[1];
    $info['address']   = $matches[2];
    $info['uuid']      = $matches[3];
    if (!empty($component)) {
      return $info[$component];
    }
    return $info;
  }
  return FALSE;
}

/**
 * Checks whether the alfresco_item node specified by reference exists.
 *
 * @param $reference
 *   A string containing an Alfresco Node Reference.
 * @param $exclude
 *   An optional Node ID (nid) to be excluded.
 * @return
 *  Returns Node ID (nid) if the alfresco_item node specified by reference
 *  exists; FALSE otherwise.
 */
function alfresco_exists_node($reference, $exclude = NULL) {

  if (!empty($exclude)) {
    $sql = "SELECT nid FROM {alfresco_node} WHERE reference = '%s' AND nid <> %d";
    if ($nid = db_result(db_query($sql, $reference, $exclude))) {
      return $nid;
    }
  }
  else {
    $sql = "SELECT nid FROM {alfresco_node} WHERE reference = '%s'";
    if ($nid = db_result(db_query($sql, $reference))) {
      return $nid;
    }
  }
  return FALSE;
}

/**
 * Shorten the title when it is too long.
 */
function alfresco_truncate_title($title, $max_length = 255) {

  $title = trim($title);
  if (drupal_strlen($title) > $max_length) {
    return drupal_substr($title, 0, $max_length - 3) .'...';
  }

  return $title;
}

/**
 * Date conversion helper function (from date_api.module)
 * No timezone conversion is done in this operation.
 */
function alfresco_date_convert($date) {

  if (empty($date) && !$date === 0) {
    return NULL;
  }

  if (!preg_match(ALFRESCO_REGEX_DATE_LOOSE, $date, $regs)) {
    return NULL;
  }

  $date = array(
    'year'   => isset($regs[1]) ? intval($regs[1]) : '',
    'month'  => isset($regs[2]) ? intval($regs[2]) : '',
    'day'    => isset($regs[3]) ? intval($regs[3]) : '',
    'hour'   => isset($regs[5]) ? intval($regs[5]) : '',
    'minute' => isset($regs[6]) ? intval($regs[6]) : '',
    'second' => isset($regs[7]) ? intval($regs[7]) : '',
  );

  return sprintf("%04d-%02d-%02d %02d:%02d:%02d",
    $date['year'], $date['month'],  $date['day'],
    $date['hour'], $date['minute'], $date['second']);
}

/**
 * Parses a Soap Fault and returns an keyed array containing the components:
 *   'code'    - Error code
 *   'message' - Error message
 *   'detail'  - Exception server name
 *
 * @see http://eirikhoem.wordpress.com/2007/08/11/soapfault-vs-exceptions/
 */
function alfresco_parse_soap_fault(SoapFault $sf) {

  if (empty($sf)) {
    return NULL;
  }

  $code = '';
  $detail = '';

  $pos = strpos($sf->faultstring, ':');
  if($pos) {
    $code = substr($sf->faultstring, 0, $pos);
    $message = trim(substr($sf->faultstring, $pos + 1, strlen($sf->faultstring)));
  }
  else {
    $message = $sf->faultstring;
  }

  if (isset($sf->detail)) {
    $reflectionObject = new ReflectionObject($sf->detail);
    $properties = $reflectionObject->getProperties();
    $exceptionName = $properties[0]->name;
    $detail = $exceptionName;
  }

  return array('code' => $code, 'message' => $message, 'detail' => $detail);
}

// ------------------------------------------------------------------
// =8 Debug helper functions
// ------------------------------------------------------------------

/**
 * Provide debug output for Alfresco.
 */
function alfresco_debug($message) {
  if (module_exists('devel') && variable_get('alfresco_debug_output', ALFRESCO_DEBUG_OUTPUT)) {
    dpm($message);
  }
}

/**
 * Shortcut to alfresco_debug()
 */
function apm($message) {
  alfresco_debug($message);
}
