<?php
// $Id$

/**
 * @file
 *
 */

/**
 *
 */
define('ALFRESCO_BROWSER_HOME', 'app:company_home');

/**
 * Implementation of hook_help().
 */
function alfresco_browser_help($path, $arg) {

  switch ($path) {
    case 'admin/help#alfresco_browser':
      return '<p>'. t('Allows users to visualize, search, browse and retrieve nodes of the Alfresco repository.') .'</p>';
  }
}

/**
 * Implementation of hook_perm().
 */
function alfresco_browser_perm() {

  return array('access alfresco browser');
}

/**
 * Implementation of hook_menu().
 */
function alfresco_browser_menu() {

  $items['alfresco/browser'] = array(
    'title' => 'Alfresco Browser Ext JS',
    'page callback' => 'alfresco_browser_page',
    'access callback' => 'user_access',
    'access arguments' => array('access alfresco browser'),
    'file' => 'alfresco_browser.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['alfresco/browser/service/tree.json'] = array(
    'page callback' => 'alfresco_browser_service_tree_json',
    'access callback' => 'user_access',
    'access arguments' => array('access alfresco browser'),
    'file' => 'alfresco_browser.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['alfresco/browser/service/grid.json'] = array(
    'page callback' => 'alfresco_browser_service_documents_json',
    'access callback' => 'user_access',
    'access arguments' => array('access alfresco browser'),
    'file' => 'alfresco_browser.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['alfresco/browser/service/download'] = array(
    'page callback' => 'alfresco_browser_service_download',
    'access callback' => 'user_access',
    'access arguments' => array('access alfresco browser'),
    'file' => 'alfresco_browser.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_theme
 */
function alfresco_browser_theme() {

  return array(
    'alfresco_browser' => array(
      'arguments' => array('element' => NULL),
    ),
    'alfresco_browser_page' => array(
      'arguments' => array(),
      'template' => 'alfresco_browser-page',
    ),
  );
}

/**
 * Process variables for book-export-html.tpl.php.
 *
 * The $variables array contains the following arguments:
 * - $title
 * - $contents
 * - $depth
 *
 * @see alfresco_browser-page.tpl.php
 */
function template_preprocess_alfresco_browser_page(&$variables) {
  global $base_path, $language;

  $variables['title'] = t('Alfresco browser');
  $variables['base_path'] = $base_path;
  $variables['module_path'] = $base_path . drupal_get_path('module', 'alfresco_browser');
  $variables['language'] = $language;
  $variables['language_rtl'] = (defined('LANGUAGE_RTL') && $language->direction == LANGUAGE_RTL) ? TRUE : FALSE;
  $variables['head'] = drupal_get_html_head();
  $variables['scripts'] = drupal_get_js();
}

/**
 * Implementation of hook_elements().
 */
function alfresco_browser_elements() {

  $type['alfresco_browser'] = array(
    '#input' => TRUE,
    '#default_value' => '',
    '#process' => array('alfresco_browser_process'),
    //'#element_validate' => array('alfresco_browser_element_validate'),
  );
  return $type;
}

/**
 * Our #process callback to expand the control.
 */
function alfresco_browser_process($element, $form_state) {

  $path = url('alfresco/browser');

  drupal_add_js("
    if (Drupal.jsEnabled) {
      var WindowObjectReference = null;
      $(document).ready(function() {
        $('#edit-alfresco-browser-button').click(function() {
          if (WindowObjectReference == null || WindowObjectReference.closed) {
            WindowObjectReference = window.open('$path', 'alfresco_browser', 'width=800,height=500,resizable');
          }
          WindowObjectReference.focus();
          return false;
        });
      });
    }", 'inline');

  $element['alfresco_browser_reference'] = array(
    '#type' => 'textfield',
    '#name' => $element['#name'],
    '#value' => $element['#value'],
    '#attributes' => array('readonly' => TRUE),
  );
  $element['alfresco_browser_button'] = array(
    '#type' => 'button',
    '#button_type' => 'browse',
    '#value' => t('Browse...'),
    '#attributes' => array('onclick' => 'return false;'),
  );
  return $element;
}

function theme_alfresco_browser($element) {
  return theme('form_element', $element, '<div class="container-inline">'. $element['#children'] .'</div>');
}
