<?php
// $Id$

/**
 * @file
 *
 */

/**
 * Implementation of hook_help().
 */
function alfresco_import_help($path, $arg) {

  switch ($path) {
    case 'admin/content/alfresco_import':
      return '<p>'. t('Import multiple alfresco nodes from a space of Alfresco.') .'</p>';
    case 'admin/help#alfresco_import':
      return '<p>'. t('Allows importing multiple alfresco nodes from a space of Alfresco.') .'</p>';
  }
}

/**
 * Implementation of hook_perm().
 */
function alfresco_import_perm() {
  return array('import alfresco contents');
}

/**
 * Implementation of hook_menu().
 */
function alfresco_import_menu() {
  $items['admin/content/alfresco_import'] = array(
    'title' => 'Alfresco import',
    'description' => 'Import alfresco item nodes from an Alfresco space.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alfresco_import_form'),
    'access arguments' => array('import alfresco contents'),
    'file' => 'alfresco_import.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/content/alfresco_import/%'] = array(
    'title' => 'Alfresco import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alfresco_import_from_space', 3),
    'access arguments' => array('import alfresco contents'),
    'file' => 'alfresco_import.pages.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_theme
 */
function alfresco_import_theme() {
  return array(
    'alfresco_import_form' => array(
      'arguments' => array('form'),
      'file' => 'alfresco_import.pages.inc',
    ),
  );
}