<?php
// $Id$

/**
 * @file
 *
 */

/**
 * Implementation of hook_help().
 */
function alfresco_import_help($path, $arg) {

  switch ($path) {
    case 'admin/content/alfresco_import':
      return '<p>'. t('Import multiple alfresco nodes from a space of Alfresco.') .'</p>';
    case 'admin/help#alfresco_import':
      return '<p>'. t('Allows importing multiple alfresco nodes from a space of Alfresco.') .'</p>';
  }
}

/**
 * Implementation of hook_perm().
 */
function alfresco_import_perm() {
  return array('import alfresco contents');
}

/**
 * Implementation of hook_menu().
 */
function alfresco_import_menu() {
  $items['admin/content/alfresco_import'] = array(
    'title' => 'Alfresco import',
    'description' => 'Import <em>Alfresco item</em> nodes from an Alfresco space.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alfresco_import_form'),
    'access arguments' => array('import alfresco contents'),
    'file' => 'alfresco_import.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/content/alfresco_test'] = array(
    'title' => 'Alfresco test',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alfresco_import_test'),
    'access arguments' => array('import alfresco contents'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_theme
 */
function alfresco_import_theme() {
  return array(
    'alfresco_import_table' => array(
      'arguments' => array('form' => NULL),
      'file' => 'alfresco_import.pages.inc',
    ),
  );
}

function alfresco_import_test() {
  $node = alfresco_create_node(
    'workspace://SpacesStore/2eb6ea26-cce1-11dd-962b-337df3af8629', TRUE,
    'Decreto 141/2006 de 18 de Julio de ordenación de la actividad cartográfica de Andalucía',
    '',
    array(52 => '')
  );

  dpm($node);

  $form = array();

  return $form;
}
